/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum Authorization {
  Granted = 'granted',
  Denied = 'denied',
  NotDetermined = 'notDetermined',
  Unsupported = 'unsupported'
}

/**
 * Read-only query for the host's notification authorization and DND state.
 *
 * The returned Promise NEVER rejects. Environmental failures collapse to
 * `{ authorization: 'unsupported', reason: 'noBundleId' | 'noAumid' | 'unsupportedPlatform' }`,
 * and library/runtime failures (panics, JoinError, unmapped HRESULTs, parse failures)
 * collapse to `reason: 'internalError'`.
 */
export declare function getNotificationStatus(): Promise<NotificationStatus>

export interface NotificationStatus {
  authorization: Authorization
  doNotDisturb: boolean
  platform: string
  reason?: Reason
}

export declare const enum Reason {
  NoBundleId = 'noBundleId',
  NoAumid = 'noAumid',
  UnsupportedPlatform = 'unsupportedPlatform',
  InternalError = 'internalError'
}
