/* auto-generated by NAPI-RS */
/* eslint-disable */
export type Authorization =  'granted'|
'denied'|
'notDetermined'|
'unsupported';

/**
 * Read-only query for the host's notification authorization and DND state.
 *
 * The returned Promise NEVER rejects. Environmental failures collapse to
 * `{ authorization: 'unsupported', reason: 'noBundleId' | 'noAumid' | 'unsupportedPlatform' }`,
 * and library/runtime failures (panics, JoinError, unmapped HRESULTs, parse failures)
 * collapse to `reason: 'internalError'`.
 */
export declare function getNotificationStatus(): Promise<NotificationStatus>

export interface NotificationStatus {
  authorization: Authorization
  doNotDisturb: boolean
  platform: string
  reason?: Reason
}

export type Reason =  'noBundleId'|
'noAumid'|
'unsupportedPlatform'|
'internalError';
